# Generated by Django 5.0.6 on 2024-07-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='role',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='Student', max_length=50),
        ),
    ]
