# Generated by Django 5.0.6 on 2024-07-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_admins_role_alter_users_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='username',
        ),
    ]
