# Generated by Django 5.0.6 on 2024-07-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_rename_user_name_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='user_name',
        ),
    ]
