# Generated by Django 5.0.6 on 2024-07-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_rename_password_hash_admins_password_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminassignments',
            table='AdminAssignments',
        ),
        migrations.AlterModelTable(
            name='admincourses',
            table='AdminCourses',
        ),
        migrations.AlterModelTable(
            name='admins',
            table='Admins',
        ),
        migrations.AlterModelTable(
            name='assignments',
            table='Assignments',
        ),
        migrations.AlterModelTable(
            name='grades',
            table='Grades',
        ),
        migrations.AlterModelTable(
            name='usercourses',
            table='UserCourses',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
