# Generated by Django 5.0.6 on 2024-07-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_adminassignments_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table='Courses',
        ),
    ]
