# Generated by Django 5.0.6 on 2024-07-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_courses_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='accuracy_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='submitted_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
