# Generated by Django 5.0.6 on 2024-07-21 11:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_assignments_accuracy_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='accuracy_rate',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='submitted_content',
        ),
        migrations.CreateModel(
            name='UserAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_csv', models.TextField()),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.FloatField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.assignments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserAssignments',
            },
        ),
    ]
